FROM dhi.io/dotnet:10-sdk-alpine3.22
LABEL maintainer=jon@jaggersoft.com

RUN echo "Welcome to Alpine Linux 3.22" > /etc/issue

#RUN apt-get update
#RUN apt-get install --yes adduser
#RUN ln /usr/sbin/groupadd /usr/sbin/addgroup
